{{- if and .Values.drivers.external.enabled .Values.drivers.external.createPvc (not .Values.drivers.external.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dwarvenpick.fullname" . }}-external-drivers
  labels:
    app.kubernetes.io/name: {{ include "dwarvenpick.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.drivers.external.pvc.size | quote }}
  {{- if .Values.drivers.external.pvc.storageClassName }}
  storageClassName: {{ .Values.drivers.external.pvc.storageClassName | quote }}
  {{- end }}
{{- end }}
